config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'tweets/about' => 'tweets#about'

  resources :tweets do
    resources :comments, only: [:create]
  end

  resources :reports do
    resources :messages, only: [:create]
  end

  root 'tweets#index'

  get 'maps/index'
    
  resources :maps, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :report
end

app/models/report.rb
class Report < ApplicationRecord
    has_many :messages, dependent: :destroy
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    has_many :comments, dependent: :destroy

    has_one_attached :image_top


    # Active Storageのバリデーション
    validates :image_top,  content_type: { in: %w[image/jpeg image/gif image/png],
                                   message: "must be a valid image format" },
                                size: { less_than: 5.megabytes,    
                                        message: "should be less than 5MB" }

                                        
    # image_top のリサイズ済み画像を返す
    def resize_image_top
        image_top.variant(resize_to_limit: [500, 200])
    end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :messages, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController      
    def create
        tweet = Tweet.find(params[:tweet_id])
        comment = tweet.comments.build(comment_params) #buildを使い、contentとtweet_idの二つを同時に代入
        
        if comment.save
            flash[:success] = "コメントしました"
            redirect_back(fallback_location: root_path) #直前のページにリダイレクト
        else
            flash[:success] = "コメントできませんでした"
            redirect_back(fallback_location: root_path) #直前のページにリダイレクト
        end
    end
      
    private
    def comment_params
      params.require(:comment).permit(:content)
    end

end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
    def index
    end
  end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def create
    report = Report.find(params[:report_id])
    message = report.messages.build(message_params) #buildを使い、contentとtweet_idの二つを同時に代入
    message.user_id = current_user.id
    if message.save
      flash[:success] = "コメントしました"
      redirect_back(fallback_location: root_path) #直前のページにリダイレクト
    else
      flash[:success] = "コメントできませんでした"
      redirect_back(fallback_location: root_path) #直前のページにリダイレクト
    end
  end

  private

    def message_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
    before_action :authenticate_user!    
        def index
            @report = Report.all
        end
   
        def new
            @report = Report.new
        end
   
        def create
            report = Report.new(report_params)
            if report.save!
                redirect_to :action => "index"
            else
                redirect_to :action => "new"
            end
        end

        def edit
            @report = Report.find(params[:id])
            @messages = @report.messages
            @message = Message.new
        end

        def update
            report = Report.find(params[:id])
            if report.update(report_params)
              redirect_to :action => "index"
            else
              redirect_to :action => "new"
            end
        end
   
        private
        def report_params
            params.require(:report).permit(:date, :place, :weather, :temperature, :sales, :number, :pricemean, :anumber, :lnumber, :knumber, :inumber)
        end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :about, :show]
  
  def index
    @tweet= Tweet.all
    if params[:search] == nil
      @tweets= Tweet.all
    elsif params[:search] == ''
      @tweets= Tweet.all
    else
      @tweets = Tweet.where("date LIKE ?", '%' + params[:search] + '%')
    end
  end

  def about
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comments = @tweet.comments
    @comment = Comment.new
  end
  
 
  def new
     @tweet = Tweet.new
  end
    
  def create
      tweet = Tweet.new(tweet_params)
      if tweet.save!
        redirect_to :action => "index"
      else
        redirect_to :action => "new"
      end
  end

  def edit
      @tweet = Tweet.find(params[:id])
  end

  def update
    tweet = Tweet.find(params[:id])
    if tweet.update(tweet_params)
      redirect_to :action => "show", :id => tweet.id
    else
      redirect_to :action => "new"
    end
  end
    
  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to action: :index
  end

  private
  def tweet_params
      params.require(:tweet).permit(:image, :date, :place, :price, :comment, :address, :lat, :lng, :image_top )
  end
  def post_params
    params.require(:post).permit(:body,:lat,:lng)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Candle</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>Candle</h1>
      <div class="header-list">
      <ul>
        <li><%= link_to "ホーム", tweets_path %></li>
        <li><%= link_to "新規投稿",new_tweet_path %></li>
        <li><%= link_to "ログイン",reports_path %></li>
      </ul>
      </div>
    </header>
    <main>
      <%= yield %>
    </main>

    <footer>
    <p>Copyright © Candle All Rights Reserved.</p>
    </footer>
  </body>

</html>

app/views/maps/index.html.erb
<h2>gmap</h2>

<input id="address" type="textbox" value="GeekSalon">
<input type="button" value="Encode" onclick="codeAddress()">

<div id="display">何かが表示される、、、、！</div>

<div id='map'></div>

<style>
#map {
  height: 600px;
  width: 600px;
}
</style>

<script>
let map

function initMap(){
  geocoder = new google.maps.Geocoder()
  map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: 40.7828, lng:-73.9653},
    zoom: 12,
  });

  marker = new google.maps.Marker({
    position:  {lat: 40.7828, lng:-73.9653},
    map: map
  });
}

let geocoder
const display = document.getElementById('display')

function codeAddress(){
  let inputAddress = document.getElementById('address').value;

  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
      map.setCenter(results[0].geometry.location);
      var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });
      display.textContent = "検索結果：" + results[ 0 ].geometry.location
    } else {
      alert('該当する結果がありませんでした：' + status);
    }
  });   
}


</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAsVPGi2ysL1GEAYk5EspuqB9FY0Lvc3eg&callback=initMap" async defer></script>


app/views/reports/edit.html.erb
<h1>キャンドル売り上げ報告</h1>
<h3>編集ページ</h3>
<%= form_for @report do |f| %>


    <div class="field">
        <%= f.label :"日付" %>
        <%= f.text_field :date, :size => 30 %>
    </div>

# データ型がstringで自由記述の入力フォーム
    <div class="field">
        <%= f.label :"会場" %>
        <%= f.text_field :place, :size => 30 %>

    </div>

    <div class="field">
        <%= f.label :"天気" %>
        <%= f.text_field :weather, :size => 30 %>

    </div>

    <div class="field">
        <%= f.label :"最高気温" %>
        <%= f.number_field :temperature, step: "0.1", :size => 30 %>

    </div>

    <div class="field">
        <%= f.label :"売り上げ"  %>
        <%= f.number_field :sales, :size => 10 %>
    </div>

    <div class="field">
        <%= f.label :"参加人数"  %>
        <%= f.number_field :number, :size => 10 %>
    </div>

    <h3>容器</h3>
    <div class="field">
        <%= f.label :"Aグラス"  %>
        <%= f.number_field :anumber, :size => 10 %>
    </div>

    <div class="field">
        <%= f.label :"Lグラス"  %>
        <%= f.number_field :lnumber, :size => 10 %>
    </div>

    <div class="field">
        <%= f.label :"Kグラス"  %>
        <%= f.number_field :knumber, :size => 10 %>
    </div>

    <div class="field">
        <%= f.label :"Iグラス"  %>
        <%= f.number_field :inumber, :size => 10 %>
    </div>




  <%= f.submit "編集する" %>
<% end %>

<div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @messages.each do |c| %>
    <div>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.content %>
    </div>
      <br>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@report, @message], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/reports/index.html.erb
<h1>売り上げ報告</h1>
<h3>一覧ページ</h3>
<%= link_to "新規投稿へ", new_report_path %>
<div class="tweets-container">
  <% @report.each do |r| %>
    <div class="report">
      <p>日付：<%= r.date %></p>
      <p>会場：<%= r.place %></p>
      <p>売上：<%= r.sales %></p>
      <p>客数：<%= r.number %></p>
      <p>Aグラス：<%= r.anumber %></p>
    </div>
    <%= link_to "編集", edit_report_path(r.id) %>
  <% end %>
</div>
<%#= link_to "ホームに戻る", tweet_path %>

app/views/reports/new.html.erb
<h1>キャンドル</h1>
<h3>売り上げ報告ページ</h3>
<%= form_for @report do |f| %>


    <div class="field">
        <%= f.label :"日付" %>
        <%= f.date_field :date, :size => 30 %>
    </div>

# データ型がstringで自由記述の入力フォーム
    <div class="field">
        <%= f.label :"会場" %>
        <%= f.text_field :place, :size => 30 %>

    </div>

    <div class="field">
        <%= f.label :"天気" %>
        <%= f.text_field :weather, :size => 30 %>

    </div>

    <div class="field">
        <%= f.label :"最高気温" %>
        <%= f.number_field :temperature, :size => 30 %>

    </div>
    
    <input type="checkbox" class="glass-check" id="glass" >
    <label  class="glass-label" for="glass">容器</label>
        <div class="glass-content">   
            <div class="field">
                <%= f.label :"Aグラス"  %>
                <%= f.number_field :anumber, :size => 10 %>
            </div>

            <div class="field">
                <%= f.label :"Lグラス"  %>
                <%= f.number_field :lnumber, :size => 10 %>
            </div>

            <div class="field">
                <%= f.label :"Kグラス"  %>
                <%= f.number_field :knumber, :size => 10 %>
            </div>

            <div class="field">
                <%= f.label :"Iグラス"  %>
                <%= f.number_field :inumber, :size => 10 %>
            </div>
        </div>
    <label for="cp_menu_bar2">menu02</label>
    <input type="radio" name="radio" id="cp_menu_bar2" class="accordion" />
    <ul id="link2">
        <li><a href="">link01</a></li>
        <li><a href="">link02</a></li>
        <li><a href="">link03</a></li>
        <li><a href="">link04</a></li>
    </ul>


    <h3>オプション</h3>
    <div class="field">
    </div>
    <div class="field">
    </div>
    <div class="field">
    </div>
    <h3>キャラクター</h3>
    <h3>ボード</h3>



  <%= f.submit "報告する" %>
<% end %>

<%= link_to "一覧に戻る", reports_path %>

app/views/tweets/about.html.erb
<h1>ジェルキャンドルとは</h1>
<div class="about-content">
    ジェルキャンドルはとうめいでゼリーのようにプニプニのロウソクです
    通常のロウソク同様熱を与えることによって液体状になるため溶かすことによって砂やガラス細工を閉じ込めることが出来ます
    ロウソクの性質上ゼリー状のまま固定されるのでそれ以上固くなることはありません

    好きなガラス細工を閉じ込めて自分だけのオリジナルなキャンドルを作りましょう！！
    
</div>

<h1>作り方</h1>
<div class="container">
    <div class="content">
        1.はじめにグラスとその中に入れるガラス細工を決めます
    </div>

    <div class="content">
        2.つぎにグラスに砂を入れます
        <p>「もよう」も作れるよ！！</p>
    </div>

    <div class="content">
        3.ガラス細工を好きなところに入れます
        <p>そっと入れてね</p>
        <p>自分の好きなところに入れてみて！！</p>
    </div>

    <div class="content">
        4.とうめいなロウソクを作品に入れます
        <p>固まるまで待っててね！</p>
    </div>

    <div class="content">
        5.冷やして固まったら完成
        <p>完成したキャンドルを渡すので戻ってきてね！</p>
    </div>
</div>

<h1>サンドアート</h1>
<div class="about-content">
    <div class="content">
        サンドアートとは
        砂にもようをつけることです
        サンドアートの一部を紹介します！
    </div>

    <div class="container">
        <h2>ウェーブ</h2>
        <div class="content">
            1.砂を3層入れます
            <p>砂は横から見るとどのくらい入ってるかわかりやすいよ</p>
            <p>一番下は入っているのが分かりにくいから他の層よりも少し多めに入れるのが〇</p>
        </div>    
        
        <div class="content">    
            2.竹ぐしをグラスに刺します
            <p>グラスに沿って入れるのがポイント！</p>
            <p>もようが出来てきている部分を自分の目の前に持ってくるとわかりやすいよ</p>
        </div>
        
        <div class="content">    
            3.最後に砂を上からかけたらウェーブの完成！！
        </div>    
    </div>
</div>
<%#= link_to "ホームに戻る", tweet_path %>

app/views/tweets/edit.html.erb
<%= form_for @tweet do |f| %>
    <div class="field">
        <%= f.label :"日付" %>
        <%= f.text_field :date, :size => 30 %>
    </div>

    <div class="field">
        <%= f.label :"会場" %>
        <%= f.text_field :place, :size => 30 %>
    </div>

    <div class="field">
        <%= f.label :"値段"  %>
        <%= f.number_field :price, :size => 10 %>
    </div>


    <div class="field">
        <%= f.label :"説明"  %>
        <%= f.text_area :comment, :size => "30x2" %>
    </div>
    
    <%= f.submit "編集する" %>
<% end %>

app/views/tweets/index.html.erb
<div class="tweets-container">
  <h3>ジェルキャンドルって？</h3>
  <div class="tweets-content">
    ジェルキャンドルはとうめいでゼリーのようにプニプニのロウソクです
    自分だけのオリジナルなキャンドルを作ろう！！
    <%= link_to "詳しく", tweets_about_path %>
  </div>
</div>

<h3>ブログ一覧</h3>

<div class="tweets-container">
  <% @tweet.each do |f| %>
    <div class="tweet">
    <%= image_tag f.resize_image_top if f.image_top.attached? %>
      日付：<%= f.date %>
      会場：<%= f.place %>
    </div>
    <%= link_to "詳細へ", tweet_path(f.id) %> 
    
  <% end %>
</div>


<h3>地図</h3>

<h4>会場を検索</h4>
 <%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
   <%= date_field_tag :search %>
   <%= submit_tag '検索する'  %>
 <% end %>

<div id='map'></div>
<style>
#map {
    height: 500px;
    width: 100%;
}
</style>

<script>
    function initMap() {

     
      let latlng = new google.maps.LatLng(38.60, 139.5);
      
      let styles = [
           {
            stylers: [
             { "saturation": 0 },
             { "lightness": 0 }
            ]
           }
          ];

      let map = new google.maps.Map(document.getElementById('map'), {
          zoom: 5.5,
          styles: styles,
          center: latlng
      });
      let transitLayer = new google.maps.TransitLayer();
      transitLayer.setMap(map);


      <% @tweets.each do |f|%>
        ( function() { 
          let markerLatLng = { lat: <%= f.lat %>, lng: <%= f.lng %> }; 
          let marker = new google.maps.Marker({ 
            position: markerLatLng, 
            map: map 
          });

          let infowindow = new google.maps.InfoWindow({
            position: markerLatLng,
            content: "<a href= '<%= tweet_url(f.id) %>' target='_blank'><%= f.place %></a>"
          });

          marker.addListener('click', function() {
            infowindow.open(map, marker);
          });

       })();
      <% end %>
       
    }
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GMAP_API'] %>&callback=initMap" async defer></script>




app/views/tweets/new.html.erb
<h1>キャンドル</h1>
<h3>新規投稿ページ</h3>
<%= form_for @tweet do |f| %>
    <div class="image-top">
        <%= f.label :image_top, '画像' %>
        <%= f.file_field :image_top, accept: "image/jpeg,image/gif,image/png" %>
    </div>

    <script type="text/javascript">
     $("#post_image_top, #post_images").bind("change", function() {
       var size_in_megabytes = this.files[0].size/1024/1024;
       if (size_in_megabytes > 5) {
         alert("Maximum file size is 5MB. Please choose a smaller file.");
         $("#post_image_top").val("");
       }
     });
    </script>

    <div class="field">
        <%= f.label :"日付" %>
        <%= f.date_field :date, :size => 30 %>
    </div>


    <div class="field">
       <%= f.label :"会場" %>
        <%= f.text_field :place, id: "address", :size => 30 %>
        <input type="button" value="検索" onclick="codeAddress()">
        <p>マーカーをドラック＆ドロップで位置の調整ができます。<p>

        
    </div>

    



    <div class="field">
        <%= f.label :"値段"  %>
        <%= f.number_field :price, :size => 10 %>
    </div>


    <div class="field">
        <%= f.label :"説明"  %>
        <%= f.text_area :comment, :size => "30x2" %>
    </div>

    <div class="field">
        <%= f.label :"住所"  %>
        <%= f.text_area :address, :size => "30x2" %>
    </div>
    
    <div class="field">
        <%= f.label :lat,"緯度" %>
        <%= f.text_field :lat, id: :lat %>
        <%= f.label :lng,"経度" %>
        <%= f.text_field :lng, id: :lng %>
    </div>

    

    <%= f.submit "投稿する" %>

    


    <h2>Map</h2>

    <div id='map'></div>

    <style>
    #map {
        height: 600px;
        width: 600px;
    }
    </style>

    <script>
    //初期マップの設定
    let map
    let marker
    function initMap(){
    geocoder = new google.maps.Geocoder()

    map = new google.maps.Map(document.getElementById('map'), {
        center:  {lat: 35.6803997, lng:139.7690174},  //東京
        zoom: 15,

    });
    }

    //検索後のマップ作成
    let geocoder
    let aft
    function codeAddress(){
        let inputAddress = document.getElementById('address').value;
        geocoder.geocode( { 'address': inputAddress}, function(results, status) {
        if (status == 'OK') {
            //マーカーが複数できないようにする
            if (aft == true){
                marker.setMap(null);
            }

            //新しくマーカーを作成する
            map.setCenter(results[0].geometry.location);
                marker = new google.maps.Marker({
                map: map,
                position: results[0].geometry.location,
                draggable: true	// ドラッグ可能にする
            });

            //二度目以降か判断
            aft = true

            //検索した時に緯度経度を入力する
            document.getElementById('lat').value = results[0].geometry.location.lat();
            document.getElementById('lng').value = results[0].geometry.location.lng();
            

            // マーカーのドロップ（ドラッグ終了）時のイベント
            google.maps.event.addListener( marker, 'dragend', function(ev){
                // イベントの引数evの、プロパティ.latLngが緯度経度
                document.getElementById('lat').value = ev.latLng.lat();
                document.getElementById('lng').value = ev.latLng.lng();
            });
        } else {
                alert('該当する結果がありませんでした：' + status);
        }
        });   
    }

    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GMAP_API'] %>&callback=initMap" async defer></script>

<% end %>    

<%#= link_to "ホームに戻る", tweet_path %>

app/views/tweets/show.html.erb
<h1>Jell Candle</h1>
<h3>ブログ詳細</h3>
<div class="tweet">
  <p><%= image_tag @tweet.resize_image_top if @tweet.image_top.attached? %>></p>
  <p>日付：<%= @tweet.date %></p>
  <p>会場：<%= @tweet.place %></p>
  <p>費用目安：<%= @tweet.price %></p>
  <p><%= @tweet.comment %></p>
  <%= button_to "削除する", tweet_path(@tweet.id), method: :delete %>
  <p>地図</p>
  <div id='map'></div>
  <style>
  #map {
    height: 400px;
    width: 100%;
  }
  </style>

  <script>
  let map

  function initMap(){
    geocoder = new google.maps.Geocoder()

    map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: <%= @tweet.lat %>, lng:<%= @tweet.lng %>},
    zoom: 12,
    });

    marker = new google.maps.Marker({
    position:  {lat: <%= @tweet.lat %>, lng:<%= @tweet.lng %>},
    map: map
    });
  }
  </script>

  <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GMAP_API'] %>&callback=initMap" async defer></script>
  
  <div class="comment-wrapper">
    <p>コメント一覧</p>
    <% @comments.each do |c| %>
      <div>
        <br>
        <%= c.content %>
      </div>
        <br>
    <% end %>

    <%= form_with(model: [@tweet, @comment], local: true) do |f| %>
        <%= f.text_area :content %>
        <%= button_tag type: "submit" do %>
          <i class="far fa-comments"></i> コメントする
        <% end %>
    <% end %>
  </div>
</div>
<%= link_to "編集", edit_tweet_path(@tweet.id) %>


<%= link_to "ホームに戻る", tweets_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>